const ZQ={
  whatsapp:'917620306562',
  currency:'₹',
  shipping:0,
  // Add your UPI ID here later if you want it displayed on checkout, e.g. 'name@upi'.
  upiId:'',
  products:[
    {id:'bracelete',name:'Bracelete',price:699,category:'Bracelets',tag:'Signature',desc:'Elevate your wrist with an exquisite bracelet designed for day-to-night styling, refined elegance and lasting shine.',image:'https://zarqaura.com/cdn/shop/files/Product_Staging-5dfed636-18a3-43a8-a2eb-9187dfc16139.jpg?v=1782814849&width=1400',images:[
      'https://zarqaura.com/cdn/shop/files/Product_Staging-5dfed636-18a3-43a8-a2eb-9187dfc16139.jpg?v=1782814849&width=1600',
      'https://zarqaura.com/cdn/shop/files/Product_Staging-839a6a82-aa61-441f-b645-795880bc2084.jpg?v=1782814849&width=1600',
      'https://zarqaura.com/cdn/shop/files/Product_Staging-11256292-bfb6-4a1a-8fae-4bf13344dfa3.jpg?v=1782814849&width=1600',
      'https://zarqaura.com/cdn/shop/files/Product_Staging-3fff3d4a-2363-4d9e-8d5a-442f5d16689c.jpg?v=1782814849&width=1600']},
    {id:'chain-bracelete',name:'Chain Bracelete',price:699,category:'Bracelets',tag:'New arrival',desc:'An everyday essential, reimagined with timeless elegance. Crafted for effortless styling, this delicate chain bracelet complements every occasion with refined simplicity and lasting shine.',image:'https://zarqaura.com/cdn/shop/files/2.1.jpg?v=1782809056&width=1400',images:[
      'https://zarqaura.com/cdn/shop/files/2.1.jpg?v=1782809056&width=1600',
      'https://zarqaura.com/cdn/shop/files/3.1.jpg?v=1782809129&width=1600',
      'https://zarqaura.com/cdn/shop/files/0_Product_Staging.jpg?v=1782809129&width=1600',
      'https://zarqaura.com/cdn/shop/files/0_Product_Staging_1.jpg?v=1782809129&width=1600']}
  ]
};
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
function money(n){return `${ZQ.currency}${Number(n).toLocaleString('en-IN')}`}
function getCart(){try{return JSON.parse(localStorage.getItem('zqCart'))||[]}catch{return[]}}
function setCart(c){localStorage.setItem('zqCart',JSON.stringify(c));refreshCartCount()}
function refreshCartCount(){const el=$('#cartCount');if(el)el.textContent=getCart().reduce((a,i)=>a+i.qty,0)}
function addToCart(id,qty=1){let c=getCart();const row=c.find(i=>i.id===id);if(row)row.qty+=qty;else c.push({id,qty});setCart(c);toast('Added to cart')}
function removeFromCart(id){setCart(getCart().filter(i=>i.id!==id));renderCart()}
function updateQty(id,delta){const c=getCart();const row=c.find(i=>i.id===id);if(!row)return;row.qty=Math.max(1,row.qty+delta);setCart(c);renderCart()}
function product(id){return ZQ.products.find(p=>p.id===id)}
function cartTotal(){return getCart().reduce((sum,i)=>{const p=product(i.id);return sum+(p?p.price*i.qty:0)},0)}
function toast(msg){let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function navInit(){const b=$('#mobileToggle'),n=$('#navlinks');if(b&&n)b.addEventListener('click',()=>n.classList.toggle('open'));refreshCartCount()}
function productCards(target='#productGrid',items=ZQ.products){const el=$(target);if(!el)return;el.innerHTML=items.map(p=>`<article class="product-card"><a class="imgwrap" href="product.html?id=${p.id}"><span class="badge">${p.tag}</span><img src="${p.image}" alt="${p.name}" loading="lazy"></a><div class="product-info"><a class="product-name" href="product.html?id=${p.id}">${p.name}</a><div class="price">${money(p.price)}</div><div class="card-actions"><button class="btn" onclick="addToCart('${p.id}')">Add to cart</button><button class="heart" aria-label="Save item">♡</button></div></div></article>`).join('')}
function renderProductPage(){const root=$('#productRoot');if(!root)return;const id=new URLSearchParams(location.search).get('id')||'chain-bracelete';const p=product(id)||ZQ.products[0];document.title=`${p.name} — ZARQAURA`;root.innerHTML=`<div><div class="gallery-main"><img id="mainProductImage" src="${p.images[0]}" alt="${p.name}"></div><div class="thumbs">${p.images.map((im,i)=>`<button class="thumb ${i===0?'active':''}" data-image="${im}"><img src="${im}" alt="${p.name} view ${i+1}"></button>`).join('')}</div></div><div class="product-panel"><div class="eyebrow">${p.category} · Anti-tarnish</div><h1 class="product-title">${p.name}</h1><div class="price" style="font-size:24px">${money(p.price)}</div><p class="product-desc">${p.desc}</p><div class="qty"><button id="qtyMinus">−</button><span id="qtyVal">1</span><button id="qtyPlus">+</button></div><div class="purchase-actions"><button class="btn" id="addProduct">Add to cart</button><button class="btn teal" id="buyNow">Buy now</button></div><div class="benefits"><div class="benefit">✦ Premium Quality Finish</div><div class="benefit">✓ Tarnish Resistant</div><div class="benefit">♡ Skin Friendly & Hypoallergenic</div><div class="benefit">◇ 6 Month Warranty</div><div class="benefit">≈ Lightweight for Daily Wear</div><div class="benefit">🚚 Free Shipping Across India</div></div><div class="accordion"><details open><summary>Product details</summary><p>Product Type: Chain Bracelet<br>Material: Premium Stainless Steel<br>Finish: High Polish<br>Color: Gold<br>Style: Minimal • Everyday • Layering<br>Occasion: Daily Wear | Office | Party | Gifting<br>Size: 18 cm + 5 cm extension chain, adjustable fit.</p></details><details><summary>Care instructions</summary><ul><li>Avoid direct contact with perfume and chemicals.</li><li>Store in the provided pouch after use.</li><li>Wipe gently with a soft cloth.</li><li>Keep away from water for longer lasting shine.</li></ul></details><details><summary>Shipping</summary><p>Free shipping on all orders. Ships within 24–48 hours. Delivery in 3–7 business days. Tracking is provided after dispatch.</p></details><details><summary>Returns</summary><p>Please see our Refund Policy for current eligibility and return instructions.</p></details></div></div>`;
  let q=1;const qv=$('#qtyVal');$('#qtyMinus').onclick=()=>{q=Math.max(1,q-1);qv.textContent=q};$('#qtyPlus').onclick=()=>{q++;qv.textContent=q};$('#addProduct').onclick=()=>addToCart(p.id,q);$('#buyNow').onclick=()=>{addToCart(p.id,q);location.href='checkout.html'};$$('.thumb').forEach(t=>t.onclick=()=>{$$('.thumb').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#mainProductImage').src=t.dataset.image})
}
function renderCart(){const box=$('#cartItems'),sum=$('#cartSummary');if(!box||!sum)return;const c=getCart();if(!c.length){box.innerHTML='<div class="empty"><h2>Your cart is empty</h2><p>Discover jewellery designed for everyday elegance.</p><a class="btn" href="shop.html">Continue shopping</a></div>';sum.innerHTML='';return}box.innerHTML=c.map(i=>{const p=product(i.id);return `<div class="cart-item"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><div class="price">${money(p.price)}</div><div class="qty"><button onclick="updateQty('${p.id}',-1)">−</button><span>${i.qty}</span><button onclick="updateQty('${p.id}',1)">+</button></div></div><div><strong>${money(p.price*i.qty)}</strong><br><button style="border:0;background:none;text-decoration:underline;cursor:pointer;margin-top:12px" onclick="removeFromCart('${p.id}')">Remove</button></div></div>`}).join('');const total=cartTotal();sum.innerHTML=`<h2 style="font-family:Lora,serif">Order summary</h2><div class="summary-row"><span>Subtotal</span><strong>${money(total)}</strong></div><div class="summary-row"><span>Shipping</span><strong>Free</strong></div><div class="summary-row total"><span>Total</span><strong>${money(total)}</strong></div><a class="btn teal" style="width:100%;margin-top:15px" href="checkout.html">Proceed to checkout</a>`}
function orderId(){const d=new Date();return 'ZQ'+d.getFullYear().toString().slice(-2)+(d.getMonth()+1).toString().padStart(2,'0')+d.getDate().toString().padStart(2,'0')+'-'+Math.random().toString(36).slice(2,6).toUpperCase()}
function buildOrder(data,id){const c=getCart();const lines=c.map(i=>{const p=product(i.id);return `• ${p.name} × ${i.qty} — ${money(p.price*i.qty)}`}).join('\n');return `Hello ZARQAURA ✨\nI would like to place an order.\n\nOrder ID: ${id}\n\nITEMS\n${lines}\n\nSubtotal: ${money(cartTotal())}\nShipping: FREE\nTOTAL: ${money(cartTotal())}\n\nCUSTOMER DETAILS\nName: ${data.name}\nPhone: ${data.phone}\nEmail: ${data.email||'-'}\nAddress: ${data.address}\nLandmark: ${data.landmark||'-'}\nCity: ${data.city}\nState: ${data.state}\nPIN: ${data.pincode}\n\nPlease confirm my order and payment details. Thank you.`}
function checkoutInit(){const f=$('#checkoutForm'),preview=$('#orderMessage'),summary=$('#checkoutSummary');if(!f||!preview||!summary)return;const c=getCart();if(!c.length){f.innerHTML='<div class="empty full"><h2>Your cart is empty</h2><a class="btn" href="shop.html">Shop now</a></div>';summary.innerHTML='';return}summary.innerHTML=c.map(i=>{const p=product(i.id);return `<div class="summary-row"><span>${p.name} × ${i.qty}</span><strong>${money(p.price*i.qty)}</strong></div>`}).join('')+`<div class="summary-row"><span>Shipping</span><strong>Free</strong></div><div class="summary-row total"><span>Total</span><strong>${money(cartTotal())}</strong></div>`;
  const id=orderId();function collect(){return Object.fromEntries(new FormData(f).entries())}function refresh(){const d=collect();preview.textContent=buildOrder({name:d.name||'[Your name]',phone:d.phone||'[Phone]',email:d.email||'',address:d.address||'[Address]',landmark:d.landmark||'',city:d.city||'[City]',state:d.state||'[State]',pincode:d.pincode||'[PIN]'},id)}f.addEventListener('input',refresh);refresh();
  $('#sendWhatsApp').onclick=(e)=>{e.preventDefault();if(!f.reportValidity())return;const data=collect();const msg=buildOrder(data,id);localStorage.setItem('zqLastOrder',JSON.stringify({id,data,message:msg,total:cartTotal(),cart:getCart(),time:new Date().toISOString()}));preview.textContent=msg;window.open(`https://wa.me/${ZQ.whatsapp}?text=${encodeURIComponent(msg)}`,'_blank','noopener');$('#successBox').classList.add('show');$('#successOrderId').textContent=id;$('#paymentText').textContent=ZQ.upiId?`Please pay ${money(cartTotal())} to UPI ID ${ZQ.upiId} and share the payment screenshot.`:`You need to complete the payment and share the snapshot. Payment details can be confirmed in the ZARQAURA WhatsApp chat.`;$('#successBox').scrollIntoView({behavior:'smooth',block:'center'})};
  $('#copyOrder').onclick=async()=>{try{await navigator.clipboard.writeText(preview.textContent);toast('Order details copied')}catch{toast('Select and copy the order details')}};
  const file=$('#paymentScreenshot');$('#shareSnapshot').onclick=()=>file.click();file.onchange=async()=>{if(!file.files[0])return;const fobj=file.files[0];const text=`Payment screenshot for ZARQAURA order ${id}.`;if(navigator.share&&navigator.canShare&&navigator.canShare({files:[fobj]})){try{await navigator.share({title:'ZARQAURA payment screenshot',text,files:[fobj]});return}catch{}}window.open(`https://wa.me/${ZQ.whatsapp}?text=${encodeURIComponent(text+' I am attaching the payment screenshot.')}`,'_blank','noopener');toast('Attach the selected screenshot in WhatsApp')};$('#openPaymentWhatsApp').onclick=()=>window.open(`https://wa.me/${ZQ.whatsapp}?text=${encodeURIComponent(`Payment update for ZARQAURA order ${id}.`)}`,'_blank','noopener')
}
function contactInit(){const f=$('#contactForm');if(!f)return;f.onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f).entries());const msg=`Hello ZARQAURA,\n\nName: ${d.name}\nPhone: ${d.phone}\nEmail: ${d.email}\n\n${d.message}`;window.open(`https://wa.me/${ZQ.whatsapp}?text=${encodeURIComponent(msg)}`,'_blank','noopener')}}
function newsletterInit(){$$('.newsletter-form').forEach(f=>f.onsubmit=e=>{e.preventDefault();const email=$('input',f).value;window.open(`https://wa.me/${ZQ.whatsapp}?text=${encodeURIComponent(`Please add ${email} to the ZARQAURA community updates.`)}`,'_blank','noopener')})}
document.addEventListener('DOMContentLoaded',()=>{navInit();productCards();renderProductPage();renderCart();checkoutInit();contactInit();newsletterInit()});
